CREATE TABLE PLAYER(
  CODE BIGINT PRIMARY KEY,
  FIRST_NAME VARCHAR(16) NOT NULL,
  LAST_NAME VARCHAR(16),
  GW_POINTS BIGINT NOT NULL,
  POSITION BIGINT NOT NULL,
  PRICE BIGINT NOT NULL,
  EXPECTED_POINTS VARCHAR(16),
  TEAM BIGINT NOT NULL
);